Victuz/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using Victuz.Data;

namespace Victuz.Controllers
{
    public class CalendarController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CalendarController(ApplicationDbContext context) {
            _context = context;
        }


        public IActionResult Calendar()
        {
            return View(_context.Activities.ToList());
        }
    }
}

Victuz/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Victuz.Data;
using Victuz.Models;

namespace Victuz.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Victuz/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Victuz.Data;
using Victuz.Models;

namespace Victuz.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Locations.ToListAsync());
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Street,HouseNumber,City,MaxCapacity")] Location location)
        {
            if (!ModelState.IsValid)
            {
                foreach (var state in ModelState)
                {
                    var key = state.Key;
                    var value = state.Value;

                    Console.WriteLine($"Key: {key}");

                    foreach (var error in value.Errors)
                    {
                        Console.WriteLine($"Error: {error.ErrorMessage}");
                    }
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Street,HouseNumber,City,MaxCapacity")] Location location)
        {
           
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Locations.FindAsync(id);
            if (location != null)
            {
                _context.Locations.Remove(location);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.Id == id);
        }
    }
}

Victuz/Controllers/SuggestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Victuz.Data;
using Victuz.Models;

namespace Victuz.Controllers
{
    public class SuggestionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SuggestionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Suggestions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Suggestions.Include(s => s.Member).ToListAsync());
        }

        // GET: Suggestions/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var suggestion = await _context.Suggestions
                .Include(s => s.Likes)
                .FirstOrDefaultAsync(s => s.Id == id);

            if (suggestion == null)
                return NotFound();

            // Haal het gebruikers-ID en de rol van de ingelogde gebruiker op
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            bool isBoardMember = User.IsInRole("BoardMember");
            bool isCreator = suggestion.MemberId == userId;
            // Bepaal het aantal likes
            int likeCount = suggestion.Likes.Count;

            // Sla de like-informatie op in ViewBag
            ViewBag.IsBoardMember = isBoardMember;
            ViewBag.LikeCount = likeCount;
            ViewBag.IsCreator = isCreator;

            // Als de gebruiker geen BoardMember is, controleer dan of hij het voorstel al geliket heeft
            if (!isBoardMember)
            {
                bool isLikedByCurrentUser = suggestion.Likes.Any(like => like.UserId == userId);
                ViewBag.IsLikedByCurrentUser = isLikedByCurrentUser;
            }

            return View(suggestion);
        }

        // POST: Suggestions/ToggleLike
        [HttpPost]
        public async Task<IActionResult> ToggleLike(int id)
        {
            var suggestion = await _context.Suggestions
                .Include(s => s.Likes)
                .FirstOrDefaultAsync(s => s.Id == id);

            if (suggestion == null)
                return NotFound();

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Controleer of de gebruiker al een like heeft gegeven
            var existingLike = suggestion.Likes.FirstOrDefault(like => like.UserId == userId);

            if (existingLike == null)
            {
                // Voeg een like toe als deze nog niet bestaat
                suggestion.Likes.Add(new Like { UserId = userId, SuggestionId = suggestion.Id });
            }
            else
            {
                // Verwijder de like als deze al bestaat
                suggestion.Likes.Remove(existingLike);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = id });
        }

        // GET: Suggestions/Create
        public IActionResult Create()
        {
            ViewBag.MemberId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View();
        }

        // POST: Suggestions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title ,Description, MemberId")] Suggestion suggestion)
        {
            if (ModelState.IsValid)
            {
                if (User.IsInRole("Member"))
                {
                    _context.Add(suggestion);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                
            }
            ViewBag.MemberId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return View(suggestion);
        }

        // GET: Suggestions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var suggestion = await _context.Suggestions.FindAsync(id);
            if (suggestion == null)
            {
                return NotFound();
            }

            return View(suggestion);
        }

        // POST: Suggestions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Description,Title, MemberId")] Suggestion suggestion)
        {
            if (id != suggestion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(suggestion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SuggestionExists(suggestion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(suggestion);
        }

        // GET: Suggestions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var suggestion = await _context.Suggestions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (suggestion == null)
            {
                return NotFound();
            }

            return View(suggestion);
        }

        // POST: Suggestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var suggestion = await _context.Suggestions.FindAsync(id);
            if (suggestion != null)
            {
                _context.Suggestions.Remove(suggestion);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SuggestionExists(int id)
        {
            return _context.Suggestions.Any(e => e.Id == id);
        }
    }
}

Victuz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Victuz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/theme.css" /> <!-- Bootswatch theme -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha384-3n3lHl8hiR3XgJrR7KwEKp0Dg5OtQZ1K4gT/AmiU8bcZAbHcKNFW5G3MLZauQ2MW" crossorigin="anonymous">

</head>
<body class="d-flex flex-column min-vh-100">
    @if (User.Identity.IsAuthenticated)
    {
        @if (User.IsInRole("Member"))
        {
            @Html.Partial("_NavbarMember")
        }
        else if (User.IsInRole("BoardMember"))
        {
            @Html.Partial("_NavbarBoardMember")
        }
        else if(User.IsInRole("Organizer"))
        {
            @Html.Partial("_NavbarOrganizer")
        }
        else
        {
            @Html.Partial("_NavbarNotLoggedIn")
        }
    }
    else
    {
        @Html.Partial("_NavbarNotLoggedIn")
    }

    <div class="container flex-grow-1">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark text-white mt-auto py-3">
        <div class="container text-center">
            <h5>Onze Partners</h5>
            <div class="partners">
                <img src="~/image/Partner 1.png" alt="Partner 1" class="img-fluid partner-logo">
                <img src="~/image/Partner 2.png" alt="Partner 2" class="img-fluid partner-logo">
            </div>
            <div class="copyright mt-2 d-flex justify-content-center align-items-center">
                <span>&copy; 2024</span> <!-- Verplaatst naar een <span> om het niet als link te maken -->
                <a href="/" class="text-white copyright-link ml-2">Victuz.</a>
                <a href="https://www.instagram.com/victuzzuyd" target="_blank" class="ml-2">
                    <img src="~/image/instagram-logo.png" alt="Volg ons op Instagram" class="instagram-logo"> <!-- Instagram logo -->
                </a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Victuz/Views/Shared/_NavbarBoardMember.cshtml
@* _NavbarNotLoggedIn.cshtml *@
<header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarColor02">
                <div class="d-flex flex-grow-1 justify-content-center">
                    <!-- Center navbar items -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Calendar" asp-action="Calendar">Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActivityModels" asp-action="Search">Zoeken</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActivityModels" asp-action="Index">Activiteiten</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/image/victuz.png" alt="Victuz Logo" style="height: 40px;">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Categorieën</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Locations" asp-action="Index">Locaties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Suggestions" asp-action="Index">Activiteit voorstellen zien</a>
                        </li>
                    </ul>
                </div>

                <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="ms-auto">
                    <!-- Align logout button to the end -->
                    @Html.AntiForgeryToken()
                    <button type="submit" class="nav-link text-light" style="cursor: pointer;">
                        Uitloggen
                    </button>
                </form>
            </div>
        </div>
    </nav>
</header>

Victuz/Views/Shared/_NavbarMember.cshtml
@* _NavbarNotLoggedIn.cshtml *@
<header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarColor02">
                <div class="d-flex flex-grow-1 justify-content-center">
                    <!-- Center navbar items -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Calendar" asp-action="Calendar">Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActivityModels" asp-action="Search">Zoeken</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/image/victuz.png" alt="Victuz Logo" style="height: 40px;">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Suggestions" asp-action="Create">Activiteit voorstel doen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Registrations" asp-action="Index">Mijn registraties</a>
                        </li>
                    </ul>
                </div>

                <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="ms-auto">
                    <!-- Align logout button to the end -->
                    @Html.AntiForgeryToken()
                    <button type="submit" class="nav-link text-light" style="cursor: pointer;">
                        Uitloggen
                    </button>
                </form>
            </div>
        </div>
    </nav>
</header>

Victuz/Views/Shared/_NavbarNotLoggedIn.cshtml
@* _NavbarNotLoggedIn.cshtml *@
<header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mx-auto">
                    
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Lid worden</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Calendar" asp-action="Calendar">Agenda</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/image/victuz.png" alt="Victuz Logo" style="height: 40px;">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="ActivityModels" asp-action="Search">Zoeken</a>
                    </li>
                </ul>
                <div class="d-flex">
                    <!-- Align LoginPartial to the end -->
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>
</header>

Victuz/Views/Shared/_NavbarOrganizer.cshtml
@* _NavbarNotLoggedIn.cshtml *@
<header>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarColor02">
                <div class="d-flex flex-grow-1 justify-content-center">
                    <!-- Center navbar items -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Calendar" asp-action="Calendar">Agenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/image/victuz.png" alt="Victuz Logo" style="height: 40px;">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActivityModels" asp-action="Search">Zoeken</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActivityModels" asp-action="Index">Activiteiten</a>
                        </li>
                    </ul>
                </div>

                <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="ms-auto">
                    <!-- Align logout button to the end -->
                    @Html.AntiForgeryToken()
                    <button type="submit" class="nav-link text-light" style="cursor: pointer;">
                        Uitloggen
                    </button>
                </form>
            </div>
        </div>
    </nav>
</header>